services:
  - type: web
    name: wppconnect
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 3000
