services:
  - type: web
    name: wpp-server
    env: docker
    buildCommand: "docker build -t wpp-server ."
    startCommand: "docker run -p 21465:21465 wpp-server"
    plan: free
    port: 21465
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
